import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Toaster } from '@/components/ui/toaster';
import { Toaster as SonnerToast } from 'sonner';
import { funnelDisplay, lexend, roboto } from './ui/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' data-theme={'custom'}>
      <body className={lexend.className}>
        <main>{children}</main>
        <Toaster />
        <SonnerToast />
      </body>
    </html>
  );
}
