import GenericCreateForm from '@/components/forms/dashboard/AddUserForm';
import { getAddresses } from '@/lib/data/data.address';
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from '@/components/ui/breadcrumb';
import { addCustomer } from '@/lib/actions/user.actions';
import { BusinessSector, Role } from '@prisma/client';

export default async function AddUserPage() {
  const addresses = await getAddresses();

  const fields = [
    {
      name: 'firstName',
      label: 'First Name',
      type: 'text',
      placeholder: 'Enter first name',
      required: true,
    },
    {
      name: 'lastName',
      label: 'Last Name',
      type: 'text',
      placeholder: 'Enter last name',
      required: true,
    },
    {
      name: 'email',
      label: 'Email',
      type: 'email',
      placeholder: '',
      required: true,
    },
    {
      name: 'password',
      label: 'Password - Will be autogenerated',
      type: 'password',
      placeholder: '**********',
      required: false,
      disabled: true,
    },
    {
      name: 'phoneNumber',
      label: 'Phone Number',
      type: 'text',
      placeholder: ' Enter phone number',
      required: true,
    },
    {
      name: 'companyNumber',
      label: 'Company Number',
      type: 'text',
      placeholder: 'Enter company number',
      required: false,
    },
  ];

  // Define select configurations
  const selectConfigs = [
    {
      name: 'addressId',
      label: 'Address',
      options: addresses.map((address) => ({
        value: address.addressId.toString(),
        label: `${address.streetName}, ${address.city}`,
      })),
    },
    {
      name: 'role',
      label: 'Role',
      options: Object.keys(Role).map((key) => ({
        value: key,
        label: Role[key as keyof typeof Role],
      })),
    },
    {
      name: 'businessSector',
      label: 'Business Sector',
      options: Object.keys(BusinessSector).map((key) => ({
        value: key,
        label: BusinessSector[key as keyof typeof BusinessSector],
      })),
    },
  ];

  return (
    <div className='container mx-auto px-4 py-8'>
      <Breadcrumb className='mb-6'>
        <BreadcrumbList>
          <BreadcrumbItem>
            <BreadcrumbLink href='/dashboard'>Home</BreadcrumbLink>
          </BreadcrumbItem>
          <BreadcrumbSeparator />
          <BreadcrumbItem>
            <BreadcrumbLink href='/dashboard/customers'>
              Customers
            </BreadcrumbLink>
          </BreadcrumbItem>
          <BreadcrumbSeparator />
          <BreadcrumbItem>
            <BreadcrumbPage>Add New</BreadcrumbPage>
          </BreadcrumbItem>
        </BreadcrumbList>
      </Breadcrumb>

      <h2 className='text-3xl font-bold tracking-tight mb-6'>
        Add New Customer
      </h2>

      {/* Pass dynamic props to AddUserForm */}
      <GenericCreateForm
        fields={fields}
        selectConfigs={selectConfigs}
        serverAction={addCustomer}
      />
    </div>
  );
}
